/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Article {
  'id' : UniqueId,
  'title' : string,
  'titleHindi' : string,
  'body' : string,
  'authorRole' : string,
  'publishedAt' : Timestamp,
  'isBreaking' : boolean,
  'author' : string,
  'imageUrl' : string,
  'isFeatured' : boolean,
  'category' : ArticleCategory,
  'bodyHindi' : string,
}
export type ArticleCategory = { 'entertainment' : null } |
  { 'technology' : null } |
  { 'business' : null } |
  { 'india' : null } |
  { 'sports' : null } |
  { 'world' : null };
export interface CitizenPost {
  'id' : UniqueId,
  'status' : CitizenPostStatus,
  'title' : string,
  'body' : string,
  'authorName' : string,
  'publishedAt' : Timestamp,
  'imageUrl' : string,
  'category' : ArticleCategory,
  'authorPrincipal' : Principal,
}
export type CitizenPostStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface Comment {
  'id' : UniqueId,
  'body' : string,
  'createdAt' : Timestamp,
  'authorName' : string,
  'articleId' : [] | [UniqueId],
  'authorPrincipal' : Principal,
  'postId' : [] | [UniqueId],
}
export interface MediaItem {
  'id' : UniqueId,
  'title' : string,
  'thumbnailUrl' : string,
  'publishedAt' : Timestamp,
  'mediaType' : MediaType,
  'embedUrl' : string,
}
export type MediaType = { 'video' : null } |
  { 'reel' : null } |
  { 'podcast' : null };
export type Timestamp = bigint;
export type UniqueId = bigint;
export interface UserProfile {
  'bio' : string,
  'name' : string,
  'avatarUrl' : string,
}
export interface UserRegistryEntry { 'role' : UserRole, 'autoId' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addComment' : ActorMethod<
    [[] | [UniqueId], [] | [UniqueId], string, string],
    UniqueId
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignRoleWithAutoId' : ActorMethod<[Principal, UserRole], string>,
  'createArticle' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      ArticleCategory,
      string,
      string,
      string,
      boolean,
      boolean,
    ],
    UniqueId
  >,
  'createCitizenPost' : ActorMethod<
    [string, string, ArticleCategory, string, string],
    UniqueId
  >,
  'deleteArticle' : ActorMethod<[UniqueId], undefined>,
  'getArticles' : ActorMethod<[], Array<Article>>,
  'getArticlesByCategory' : ActorMethod<[ArticleCategory], Array<Article>>,
  'getBreakingNews' : ActorMethod<[], Array<Article>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCitizenPosts' : ActorMethod<[], Array<CitizenPost>>,
  'getCommentsByArticle' : ActorMethod<[UniqueId], Array<Comment>>,
  'getCommentsByPost' : ActorMethod<[UniqueId], Array<Comment>>,
  'getFeaturedArticles' : ActorMethod<[], Array<Article>>,
  'getMediaItems' : ActorMethod<[], Array<MediaItem>>,
  'getMyProfile' : ActorMethod<[], [] | [UserRegistryEntry]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserRegistry' : ActorMethod<
    [],
    Array<{ 'principal' : Principal, 'role' : UserRole, 'autoId' : string }>
  >,
  'initialize' : ActorMethod<[], undefined>,
  'isAdminCaller' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isEditorCaller' : ActorMethod<[], boolean>,
  'revokeRole' : ActorMethod<[Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateArticleStatus' : ActorMethod<[UniqueId, CitizenPostStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];