/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UniqueId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ArticleCategory = IDL.Variant({
  'entertainment' : IDL.Null,
  'technology' : IDL.Null,
  'business' : IDL.Null,
  'india' : IDL.Null,
  'sports' : IDL.Null,
  'world' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const Article = IDL.Record({
  'id' : UniqueId,
  'title' : IDL.Text,
  'titleHindi' : IDL.Text,
  'body' : IDL.Text,
  'authorRole' : IDL.Text,
  'publishedAt' : Timestamp,
  'isBreaking' : IDL.Bool,
  'author' : IDL.Text,
  'imageUrl' : IDL.Text,
  'isFeatured' : IDL.Bool,
  'category' : ArticleCategory,
  'bodyHindi' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'avatarUrl' : IDL.Text,
});
export const CitizenPostStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const CitizenPost = IDL.Record({
  'id' : UniqueId,
  'status' : CitizenPostStatus,
  'title' : IDL.Text,
  'body' : IDL.Text,
  'authorName' : IDL.Text,
  'publishedAt' : Timestamp,
  'imageUrl' : IDL.Text,
  'category' : ArticleCategory,
  'authorPrincipal' : IDL.Principal,
});
export const Comment = IDL.Record({
  'id' : UniqueId,
  'body' : IDL.Text,
  'createdAt' : Timestamp,
  'authorName' : IDL.Text,
  'articleId' : IDL.Opt(UniqueId),
  'authorPrincipal' : IDL.Principal,
  'postId' : IDL.Opt(UniqueId),
});
export const MediaType = IDL.Variant({
  'video' : IDL.Null,
  'reel' : IDL.Null,
  'podcast' : IDL.Null,
});
export const MediaItem = IDL.Record({
  'id' : UniqueId,
  'title' : IDL.Text,
  'thumbnailUrl' : IDL.Text,
  'publishedAt' : Timestamp,
  'mediaType' : MediaType,
  'embedUrl' : IDL.Text,
});
export const UserRegistryEntry = IDL.Record({
  'role' : UserRole,
  'autoId' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func(
      [IDL.Opt(UniqueId), IDL.Opt(UniqueId), IDL.Text, IDL.Text],
      [UniqueId],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignRoleWithAutoId' : IDL.Func([IDL.Principal, UserRole], [IDL.Text], []),
  'createArticle' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        ArticleCategory,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
        IDL.Bool,
      ],
      [UniqueId],
      [],
    ),
  'createCitizenPost' : IDL.Func(
      [IDL.Text, IDL.Text, ArticleCategory, IDL.Text, IDL.Text],
      [UniqueId],
      [],
    ),
  'deleteArticle' : IDL.Func([UniqueId], [], []),
  'getArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
  'getArticlesByCategory' : IDL.Func(
      [ArticleCategory],
      [IDL.Vec(Article)],
      ['query'],
    ),
  'getBreakingNews' : IDL.Func([], [IDL.Vec(Article)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCitizenPosts' : IDL.Func([], [IDL.Vec(CitizenPost)], ['query']),
  'getCommentsByArticle' : IDL.Func([UniqueId], [IDL.Vec(Comment)], ['query']),
  'getCommentsByPost' : IDL.Func([UniqueId], [IDL.Vec(Comment)], ['query']),
  'getFeaturedArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
  'getMediaItems' : IDL.Func([], [IDL.Vec(MediaItem)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserRegistryEntry)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserRegistry' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Record({
            'principal' : IDL.Principal,
            'role' : UserRole,
            'autoId' : IDL.Text,
          })
        ),
      ],
      ['query'],
    ),
  'initialize' : IDL.Func([], [], []),
  'isAdminCaller' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isEditorCaller' : IDL.Func([], [IDL.Bool], ['query']),
  'revokeRole' : IDL.Func([IDL.Principal], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateArticleStatus' : IDL.Func([UniqueId, CitizenPostStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UniqueId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ArticleCategory = IDL.Variant({
    'entertainment' : IDL.Null,
    'technology' : IDL.Null,
    'business' : IDL.Null,
    'india' : IDL.Null,
    'sports' : IDL.Null,
    'world' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const Article = IDL.Record({
    'id' : UniqueId,
    'title' : IDL.Text,
    'titleHindi' : IDL.Text,
    'body' : IDL.Text,
    'authorRole' : IDL.Text,
    'publishedAt' : Timestamp,
    'isBreaking' : IDL.Bool,
    'author' : IDL.Text,
    'imageUrl' : IDL.Text,
    'isFeatured' : IDL.Bool,
    'category' : ArticleCategory,
    'bodyHindi' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'avatarUrl' : IDL.Text,
  });
  const CitizenPostStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const CitizenPost = IDL.Record({
    'id' : UniqueId,
    'status' : CitizenPostStatus,
    'title' : IDL.Text,
    'body' : IDL.Text,
    'authorName' : IDL.Text,
    'publishedAt' : Timestamp,
    'imageUrl' : IDL.Text,
    'category' : ArticleCategory,
    'authorPrincipal' : IDL.Principal,
  });
  const Comment = IDL.Record({
    'id' : UniqueId,
    'body' : IDL.Text,
    'createdAt' : Timestamp,
    'authorName' : IDL.Text,
    'articleId' : IDL.Opt(UniqueId),
    'authorPrincipal' : IDL.Principal,
    'postId' : IDL.Opt(UniqueId),
  });
  const MediaType = IDL.Variant({
    'video' : IDL.Null,
    'reel' : IDL.Null,
    'podcast' : IDL.Null,
  });
  const MediaItem = IDL.Record({
    'id' : UniqueId,
    'title' : IDL.Text,
    'thumbnailUrl' : IDL.Text,
    'publishedAt' : Timestamp,
    'mediaType' : MediaType,
    'embedUrl' : IDL.Text,
  });
  const UserRegistryEntry = IDL.Record({
    'role' : UserRole,
    'autoId' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func(
        [IDL.Opt(UniqueId), IDL.Opt(UniqueId), IDL.Text, IDL.Text],
        [UniqueId],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignRoleWithAutoId' : IDL.Func(
        [IDL.Principal, UserRole],
        [IDL.Text],
        [],
      ),
    'createArticle' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          ArticleCategory,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
          IDL.Bool,
        ],
        [UniqueId],
        [],
      ),
    'createCitizenPost' : IDL.Func(
        [IDL.Text, IDL.Text, ArticleCategory, IDL.Text, IDL.Text],
        [UniqueId],
        [],
      ),
    'deleteArticle' : IDL.Func([UniqueId], [], []),
    'getArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
    'getArticlesByCategory' : IDL.Func(
        [ArticleCategory],
        [IDL.Vec(Article)],
        ['query'],
      ),
    'getBreakingNews' : IDL.Func([], [IDL.Vec(Article)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCitizenPosts' : IDL.Func([], [IDL.Vec(CitizenPost)], ['query']),
    'getCommentsByArticle' : IDL.Func(
        [UniqueId],
        [IDL.Vec(Comment)],
        ['query'],
      ),
    'getCommentsByPost' : IDL.Func([UniqueId], [IDL.Vec(Comment)], ['query']),
    'getFeaturedArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
    'getMediaItems' : IDL.Func([], [IDL.Vec(MediaItem)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserRegistryEntry)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserRegistry' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Record({
              'principal' : IDL.Principal,
              'role' : UserRole,
              'autoId' : IDL.Text,
            })
          ),
        ],
        ['query'],
      ),
    'initialize' : IDL.Func([], [], []),
    'isAdminCaller' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isEditorCaller' : IDL.Func([], [IDL.Bool], ['query']),
    'revokeRole' : IDL.Func([IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateArticleStatus' : IDL.Func([UniqueId, CitizenPostStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };