/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Article {
    id: UniqueId;
    title: string;
    titleHindi: string;
    body: string;
    authorRole: string;
    publishedAt: Timestamp;
    isBreaking: boolean;
    author: string;
    imageUrl: string;
    isFeatured: boolean;
    category: ArticleCategory;
    bodyHindi: string;
}
export type Timestamp = bigint;
export interface Comment {
    id: UniqueId;
    body: string;
    createdAt: Timestamp;
    authorName: string;
    articleId?: UniqueId;
    authorPrincipal: Principal;
    postId?: UniqueId;
}
export type UniqueId = bigint;
export interface UserRegistryEntry {
    role: UserRole;
    autoId: string;
}
export interface MediaItem {
    id: UniqueId;
    title: string;
    thumbnailUrl: string;
    publishedAt: Timestamp;
    mediaType: MediaType;
    embedUrl: string;
}
export interface UserProfile {
    bio: string;
    name: string;
    avatarUrl: string;
}
export interface CitizenPost {
    id: UniqueId;
    status: CitizenPostStatus;
    title: string;
    body: string;
    authorName: string;
    publishedAt: Timestamp;
    imageUrl: string;
    category: ArticleCategory;
    authorPrincipal: Principal;
}
export enum ArticleCategory {
    entertainment = "entertainment",
    technology = "technology",
    business = "business",
    india = "india",
    sports = "sports",
    world = "world"
}
export enum CitizenPostStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum MediaType {
    video = "video",
    reel = "reel",
    podcast = "podcast"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addComment(articleId: UniqueId | null, postId: UniqueId | null, authorName: string, body: string): Promise<UniqueId>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignRoleWithAutoId(user: Principal, role: UserRole): Promise<string>;
    createArticle(title: string, titleHindi: string, body: string, bodyHindi: string, category: ArticleCategory, author: string, authorRole: string, imageUrl: string, isBreaking: boolean, isFeatured: boolean): Promise<UniqueId>;
    createCitizenPost(title: string, body: string, category: ArticleCategory, authorName: string, imageUrl: string): Promise<UniqueId>;
    getArticles(): Promise<Array<Article>>;
    getArticlesByCategory(category: ArticleCategory): Promise<Array<Article>>;
    getBreakingNews(): Promise<Array<Article>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCitizenPosts(): Promise<Array<CitizenPost>>;
    getCommentsByArticle(articleId: UniqueId): Promise<Array<Comment>>;
    getFeaturedArticles(): Promise<Array<Article>>;
    getMediaItems(): Promise<Array<MediaItem>>;
    getMyProfile(): Promise<UserRegistryEntry | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserRegistry(): Promise<Array<{
        principal: Principal;
        role: UserRole;
        autoId: string;
    }>>;
    initialize(): Promise<void>;
    isAdminCaller(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    isEditorCaller(): Promise<boolean>;
    revokeRole(user: Principal): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateArticleStatus(postId: UniqueId, newStatus: CitizenPostStatus): Promise<void>;
}
import type { Article as _Article, ArticleCategory as _ArticleCategory, CitizenPost as _CitizenPost, CitizenPostStatus as _CitizenPostStatus, Comment as _Comment, MediaItem as _MediaItem, MediaType as _MediaType, Timestamp as _Timestamp, UniqueId as _UniqueId, UserProfile as _UserProfile, UserRegistryEntry as _UserRegistryEntry, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addComment(arg0: UniqueId | null, arg1: UniqueId | null, arg2: string, arg3: string): Promise<UniqueId> {
        if (this.processError) {
            try {
                const result = await this.actor.addComment(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addComment(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n2(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n2(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignRoleWithAutoId(arg0: Principal, arg1: UserRole): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.assignRoleWithAutoId(arg0, to_candid_UserRole_n2(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignRoleWithAutoId(arg0, to_candid_UserRole_n2(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createArticle(arg0: string, arg1: string, arg2: string, arg3: string, arg4: ArticleCategory, arg5: string, arg6: string, arg7: string, arg8: boolean, arg9: boolean): Promise<UniqueId> {
        if (this.processError) {
            try {
                const result = await this.actor.createArticle(arg0, arg1, arg2, arg3, to_candid_ArticleCategory_n4(this._uploadFile, this._downloadFile, arg4), arg5, arg6, arg7, arg8, arg9);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createArticle(arg0, arg1, arg2, arg3, to_candid_ArticleCategory_n4(this._uploadFile, this._downloadFile, arg4), arg5, arg6, arg7, arg8, arg9);
            return result;
        }
    }
    async createCitizenPost(arg0: string, arg1: string, arg2: ArticleCategory, arg3: string, arg4: string): Promise<UniqueId> {
        if (this.processError) {
            try {
                const result = await this.actor.createCitizenPost(arg0, arg1, to_candid_ArticleCategory_n4(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCitizenPost(arg0, arg1, to_candid_ArticleCategory_n4(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
            return result;
        }
    }
    async getArticles(): Promise<Array<Article>> {
        if (this.processError) {
            try {
                const result = await this.actor.getArticles();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getArticles();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getArticlesByCategory(arg0: ArticleCategory): Promise<Array<Article>> {
        if (this.processError) {
            try {
                const result = await this.actor.getArticlesByCategory(to_candid_ArticleCategory_n4(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getArticlesByCategory(to_candid_ArticleCategory_n4(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBreakingNews(): Promise<Array<Article>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBreakingNews();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBreakingNews();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCitizenPosts(): Promise<Array<CitizenPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCitizenPosts();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCitizenPosts();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCommentsByArticle(arg0: UniqueId): Promise<Array<Comment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCommentsByArticle(arg0);
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCommentsByArticle(arg0);
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFeaturedArticles(): Promise<Array<Article>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeaturedArticles();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeaturedArticles();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMediaItems(): Promise<Array<MediaItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMediaItems();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMediaItems();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(): Promise<UserRegistryEntry | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserRegistry(): Promise<Array<{
        principal: Principal;
        role: UserRole;
        autoId: string;
    }>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserRegistry();
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserRegistry();
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async initialize(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initialize();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initialize();
            return result;
        }
    }
    async isAdminCaller(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdminCaller();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdminCaller();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isEditorCaller(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isEditorCaller();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isEditorCaller();
            return result;
        }
    }
    async revokeRole(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.revokeRole(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.revokeRole(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateArticleStatus(arg0: UniqueId, arg1: CitizenPostStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateArticleStatus(arg0, to_candid_CitizenPostStatus_n33(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateArticleStatus(arg0, to_candid_CitizenPostStatus_n33(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_ArticleCategory_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ArticleCategory): ArticleCategory {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Article_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Article): Article {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_CitizenPostStatus_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CitizenPostStatus): CitizenPostStatus {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_CitizenPost_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CitizenPost): CitizenPost {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Comment_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Comment): Comment {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_MediaItem_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MediaItem): MediaItem {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_MediaType_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MediaType): MediaType {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_UserRegistryEntry_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRegistryEntry): UserRegistryEntry {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UniqueId]): UniqueId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserRegistryEntry]): UserRegistryEntry | null {
    return value.length === 0 ? null : from_candid_UserRegistryEntry_n29(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UniqueId;
    status: _CitizenPostStatus;
    title: string;
    body: string;
    authorName: string;
    publishedAt: _Timestamp;
    imageUrl: string;
    category: _ArticleCategory;
    authorPrincipal: Principal;
}): {
    id: UniqueId;
    status: CitizenPostStatus;
    title: string;
    body: string;
    authorName: string;
    publishedAt: Timestamp;
    imageUrl: string;
    category: ArticleCategory;
    authorPrincipal: Principal;
} {
    return {
        id: value.id,
        status: from_candid_CitizenPostStatus_n17(_uploadFile, _downloadFile, value.status),
        title: value.title,
        body: value.body,
        authorName: value.authorName,
        publishedAt: value.publishedAt,
        imageUrl: value.imageUrl,
        category: from_candid_ArticleCategory_n9(_uploadFile, _downloadFile, value.category),
        authorPrincipal: value.authorPrincipal
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UniqueId;
    body: string;
    createdAt: _Timestamp;
    authorName: string;
    articleId: [] | [_UniqueId];
    authorPrincipal: Principal;
    postId: [] | [_UniqueId];
}): {
    id: UniqueId;
    body: string;
    createdAt: Timestamp;
    authorName: string;
    articleId?: UniqueId;
    authorPrincipal: Principal;
    postId?: UniqueId;
} {
    return {
        id: value.id,
        body: value.body,
        createdAt: value.createdAt,
        authorName: value.authorName,
        articleId: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.articleId)),
        authorPrincipal: value.authorPrincipal,
        postId: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.postId))
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UniqueId;
    title: string;
    thumbnailUrl: string;
    publishedAt: _Timestamp;
    mediaType: _MediaType;
    embedUrl: string;
}): {
    id: UniqueId;
    title: string;
    thumbnailUrl: string;
    publishedAt: Timestamp;
    mediaType: MediaType;
    embedUrl: string;
} {
    return {
        id: value.id,
        title: value.title,
        thumbnailUrl: value.thumbnailUrl,
        publishedAt: value.publishedAt,
        mediaType: from_candid_MediaType_n26(_uploadFile, _downloadFile, value.mediaType),
        embedUrl: value.embedUrl
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    role: _UserRole;
    autoId: string;
}): {
    role: UserRole;
    autoId: string;
} {
    return {
        role: from_candid_UserRole_n12(_uploadFile, _downloadFile, value.role),
        autoId: value.autoId
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: Principal;
    role: _UserRole;
    autoId: string;
}): {
    principal: Principal;
    role: UserRole;
    autoId: string;
} {
    return {
        principal: value.principal,
        role: from_candid_UserRole_n12(_uploadFile, _downloadFile, value.role),
        autoId: value.autoId
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UniqueId;
    title: string;
    titleHindi: string;
    body: string;
    authorRole: string;
    publishedAt: _Timestamp;
    isBreaking: boolean;
    author: string;
    imageUrl: string;
    isFeatured: boolean;
    category: _ArticleCategory;
    bodyHindi: string;
}): {
    id: UniqueId;
    title: string;
    titleHindi: string;
    body: string;
    authorRole: string;
    publishedAt: Timestamp;
    isBreaking: boolean;
    author: string;
    imageUrl: string;
    isFeatured: boolean;
    category: ArticleCategory;
    bodyHindi: string;
} {
    return {
        id: value.id,
        title: value.title,
        titleHindi: value.titleHindi,
        body: value.body,
        authorRole: value.authorRole,
        publishedAt: value.publishedAt,
        isBreaking: value.isBreaking,
        author: value.author,
        imageUrl: value.imageUrl,
        isFeatured: value.isFeatured,
        category: from_candid_ArticleCategory_n9(_uploadFile, _downloadFile, value.category),
        bodyHindi: value.bodyHindi
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    entertainment: null;
} | {
    technology: null;
} | {
    business: null;
} | {
    india: null;
} | {
    sports: null;
} | {
    world: null;
}): ArticleCategory {
    return "entertainment" in value ? ArticleCategory.entertainment : "technology" in value ? ArticleCategory.technology : "business" in value ? ArticleCategory.business : "india" in value ? ArticleCategory.india : "sports" in value ? ArticleCategory.sports : "world" in value ? ArticleCategory.world : value;
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): CitizenPostStatus {
    return "pending" in value ? CitizenPostStatus.pending : "approved" in value ? CitizenPostStatus.approved : "rejected" in value ? CitizenPostStatus.rejected : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    video: null;
} | {
    reel: null;
} | {
    podcast: null;
}): MediaType {
    return "video" in value ? MediaType.video : "reel" in value ? MediaType.reel : "podcast" in value ? MediaType.podcast : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CitizenPost>): Array<CitizenPost> {
    return value.map((x)=>from_candid_CitizenPost_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Comment>): Array<Comment> {
    return value.map((x)=>from_candid_Comment_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MediaItem>): Array<MediaItem> {
    return value.map((x)=>from_candid_MediaItem_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<{
    principal: Principal;
    role: _UserRole;
    autoId: string;
}>): Array<{
    principal: Principal;
    role: UserRole;
    autoId: string;
}> {
    return value.map((x)=>from_candid_record_n32(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Article>): Array<Article> {
    return value.map((x)=>from_candid_Article_n7(_uploadFile, _downloadFile, x));
}
function to_candid_ArticleCategory_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ArticleCategory): _ArticleCategory {
    return to_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function to_candid_CitizenPostStatus_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CitizenPostStatus): _CitizenPostStatus {
    return to_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UniqueId | null): [] | [_UniqueId] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CitizenPostStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == CitizenPostStatus.pending ? {
        pending: null
    } : value == CitizenPostStatus.approved ? {
        approved: null
    } : value == CitizenPostStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ArticleCategory): {
    entertainment: null;
} | {
    technology: null;
} | {
    business: null;
} | {
    india: null;
} | {
    sports: null;
} | {
    world: null;
} {
    return value == ArticleCategory.entertainment ? {
        entertainment: null
    } : value == ArticleCategory.technology ? {
        technology: null
    } : value == ArticleCategory.business ? {
        business: null
    } : value == ArticleCategory.india ? {
        india: null
    } : value == ArticleCategory.sports ? {
        sports: null
    } : value == ArticleCategory.world ? {
        world: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
